[package]
name = "prosolo"
version = "0.4.0"
authors = ["David Laehnemann <david.laehnemann@hhu.de>"]

[dependencies]
# libprosic = { git = "https://github.com/PROSIC/libprosic", rev = "607b3dc4f3f260e182985763385a0dbecee38e8a" }
libprosic = { path = "../libprosic" }
clap = {version = "2.24.*", features = ["yaml", "color", "suggestions"]}
# rust-htslib = "0.17.0"
rust-htslib = { git="https://github.com/rust-bio/rust-htslib.git", rev="2718cb3c9ee9f840ed8dda57898fb43938ec707a" }
# bio = { git="https://github.com/rust-bio/rust-bio.git", branch="master" }
# bio = "0.21.0"
bio = { git="https://github.com/rust-bio/rust-bio.git", rev="de17d56f1107eb94770aed6e0378cab04a75d4ed" }
log = "0.3.*"
fern = "0.3.*"
csv = "0.14.*"
itertools = "0.4.*"
time = "*"
serde_json = "1.0"
# flame = { version = "0.2.2", optional = true }
flame = { git = "https://github.com/TyOverby/flame.git", branch = "master", optional = true }
flamer = { version = "^0.2.3", optional = true }

[dev-dependencies]
cli_test_dir = "^0.1"
regex = "^0.2"

[features]
default = []
flame_it = ["flame", "flamer", "libprosic/flame_it"]
flame_it_details = ["flame", "flamer", "libprosic/flame_it", "libprosic/flame_it_details"]

[profile.release]
debug = true
