[package]
name = "prosolo"
version = "0.2.0"
authors = ["David Laehnemann <david.laehnemann@hhu.de>"]

[dependencies]
#libprosic = "0.3.*"
libprosic = { git  = "https://github.com/PROSIC/libprosic/", rev = "057aba04adf7e5d2eda93b1f3fadce3370c9a965"}
clap = {version = "2.10.*", features = ["yaml", "color", "suggestions"]}
rust-htslib = "0.12.*"
bio = "0.14.*"
log = "0.3.*"
fern = "0.3.*"
csv = "0.14.*"
itertools = "0.4.*"
time = "*"
rustc-serialize = "0.3.*"
flame = { version = "^0.1.2", optional = true }
flamer = { version = "^0.1.2", optional = true }

[dev-dependencies]
cli_test_dir = "^0.1"
regex = "^0.2"

[features]
default = []
flame_it = ["flame", "flamer", "libprosic/flame_it"]
